const { CallTracker } = require("assert");

module.exports = [
  {
    id: 1,
    name: "Quiet Café",
    cost: 150,
    duration: 60,
    moodTags: ["quiet", "relaxed"],
    distance: "near",
    crowdLevel: "low",
    indoor: true,
    energyLevel: "low",
    category:"food",
    location:{x:3,y:2},
    description:""
  },
  {
    id: 2,
    name: "Campus Walk",
    cost: 0,
    duration: 45,
    moodTags: ["relaxed"],
    distance: "near",
    crowdLevel: "low",
    indoor: false,
    energyLevel: "medium",
    category:"relaxed",
    location:{x:3,y:3},
    description:""
  },
  {
    id: 3,
    name: "Student Hangout Spot",
    cost: 200,
    duration: 90,
    moodTags: ["social"],
    distance: "medium",
    crowdLevel: "high",
    indoor: true,
    energyLevel: "medium",
    category:"social",
    location:{x:1,y:0},
    description:""
  },
  {
    id: 4,
    name: "Library Study Break",
    cost: 0,
    duration: 60,
    moodTags: ["productive", "quiet"],
    distance: "near",
    crowdLevel: "low",
    indoor: true,
    energyLevel: "low",
    category:"study",
    location:{x:1,y:1},
    description:""
  },
  {
    id: 5,
    name: "Local Food Court",
    cost: 180,
    duration: 75,
    moodTags: ["social"],
    distance: "near",
    crowdLevel: "medium",
    indoor: true,
    energyLevel: "medium",
    category:"food",
    location:{x:1,y:1},
    description:""
  },
  {
    id: 6,
    name: "Evening Park Visit",
    cost: 0,
    duration: 60,
    moodTags: ["relaxed", "quiet"],
    distance: "medium",
    crowdLevel: "low",
    indoor: false,
    energyLevel: "low",
    category:"outdoor",
    location:{x:3,y:3},
    description:""
  },
  {
    id: 7,
    name: "Movie Screening",
    cost: 250,
    duration: 120,
    moodTags: ["relaxed"],
    distance: "far",
    crowdLevel: "medium",
    indoor: true,
    energyLevel: "low",
    category:"entertainment",
    location:{x:5,y:3},
    description:""
  },
  {
    id: 8,
    name: "Sports Ground Session",
    cost: 0,
    duration: 90,
    moodTags: ["energetic"],
    distance: "near",
    crowdLevel: "medium",
    indoor: false,
    energyLevel: "high",
    category:"outdoor",
    location:{x:6,y:2},
    description:""
  },
  {
    id: 9,
    name: "Art Club Meetup",
    cost: 100,
    duration: 75,
    moodTags: ["creative", "social"],
    distance: "medium",
    crowdLevel: "low",
    indoor: true,
    energyLevel: "medium",
    category:"social",
    location:{x:4,y:2},
    description:""
  },
  {
    id: 10,
    name: "Bookstore Visit",
    cost: 50,
    duration: 45,
    moodTags: ["quiet"],
    distance: "near",
    crowdLevel: "low",
    indoor: true,
    energyLevel: "low",
    category:"relaxed",
    location:{x:3,y:5},
    description:""
  }
];